### ISSUE TITLE
Error: Missing dependencies for SOCKS support.

### ISSUE THREAD

**Issue by TrezorHannes** [dsbaars/lnd-lnurl#2]
#### Environment: 
- Umbrel with LND 0.14.1-beta commit=v0.14.1-beta
- Installed via git-clone + pip3 install requirements, not DOCKER
- Python3

#### cat umbrel/.env
```
TOR_PROXY_IP=10.21.21.11
TOR_PROXY_PORT=9050
```

#### cat lndlnurl.umbrel.conf
```
[lnd]
tlscertpath = /home/umbrel/.lnd/tls.cert
macaroonpath = /home/umbrel/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
restserver = 10.21.21.9:8080
rpcserver = 10.21.21.9:10009

[tor]
active = true
socks = 10.21.21.11:9050
```

#### Command
```
python3 main.py LNURL1DP68GURN8GHJ7MRWW3UXYMM59E3K7MF0D3H82UNV9ACXZ7FLW4EK2UNFVS7NXWPKXSURYYAF0CA -c lndlnurl.umbrel.conf
onnected with node HODLmeTight (LND 0.14.1-beta commit=v0.14.1-beta)
--------------------------------------------------------------------------------
Error: Missing dependencies for SOCKS support.
```

Any way to better identify what dependencies are missing?

**Comment by dsbaars** [comment]
That's quite weird, PySocks should work... Tested with Python 3.9 on Debian Buster and Alpine 3.14.
`requests` should support that since version 2.10, and in the `requirements.txt` it asks for version 2.26.
If you have an older version you could try `requests[socks]` but again, if you installed packages from requirements it should work.

What is the exact Python version you are using? I tested with 3.9.1 and 3.9.9. Docker image uses 3.9.9

**Comment by TrezorHannes** [comment]
I'm quite certain my python3 version was the culprit. I've updated last week or so, from 3.10 > 3.7.3 and now it's working fine

```
Connected with node HODLmeTight (LND 0.14.1-beta commit=v0.14.1-beta)
--------------------------------------------------------------------------------
Metadata: Fund @djurib account on t.me/lntxbot.
Pay Request - Min 100 / Max 1000000 satoshi
How much do you want to pay (in sats):
```

Thanks for looking into this.
